# Generated by Django 4.2.4 on 2023-08-18 13:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0003_topic_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('title', models.CharField(max_length=200, verbose_name='موضوع')),
                ('instruction', ckeditor.fields.RichTextField(blank=True, verbose_name='راهنما')),
                ('URL', models.URLField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.topic', verbose_name='مبحث')),
            ],
            options={
                'verbose_name': 'تمرین',
                'verbose_name_plural': 'تمارین',
                'ordering': ('created', 'updated'),
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='exercise.exercise')),
            ],
            options={
                'verbose_name': 'راهنمایی',
                'verbose_name_plural': 'راهنمایی ها',
                'ordering': ('exercise',),
            },
        ),
    ]
