# Generated by Django 4.2.4 on 2023-08-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tip',
            new_name='ExerciseTip',
        ),
    ]
