# Generated by Django 4.2.4 on 2023-08-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_rename_tip_exercisetip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='URL',
            field=models.CharField(max_length=200),
        ),
    ]
